version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    env_file: ./.env
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    networks:
      - backend

  web:
    image: runnerpia
    container_name: runnerpia
    build:
      context: '.'
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - db
      # - redis
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis
    env_file: ./.env
    restart: always
    ports:
      - 6379:6379
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

networks:
  backend:
